### ISSUE TITLE
Mapeamento do Fluxo de Utilização da Solução

### ISSUE THREAD

**Issue by laurapbueno** [Inteli-College/2024-T0008-EC05-G03#26]
- [x] A partir das Users Stories, selecione o principal fluxo de utilização de cada Persona
- [x] Construa um mapa que represente o fluxo da utilização da solução proposta pelo grupo, mostrando os pontos nos quais os componentes específicos da solução são utilizados, dados são trocados e respostas são devolvidas visualmente na forma de telas.

**Comment by rafaelarojas** [comment]
MAPEAMENTO DO FLUXO DE UTILIZAÇÃO DA SOLUÇÃO -
Descrição do Artefato
No artefato da Sprint 1 você realizou o mapeamento das Jornadas de Usuário e das
User Stories referentes às Personas que utilizarão a solução que você pretende
desenvolver. Depois de validar essas Jornadas com o parceiro e realizar os devidos ajustes,
no presente mapeamento você desenvolverá um mapeamento que leva em consideração
componentes e telas da sua solução.

O que o aluno deve **entregar**
Siga os passos abaixo para completar o artefato:
A. Partindo das Jornadas do Usuário validadas com o parceiro e posteriormente
ajustadas, bem como das User Stories identificadas, selecione o principal
fluxo de utilização de cada Persona. Por exemplo: O funcionário da
manutenção, deseja utilizar minha solução para separar materiais utilizando
um braço robótico, registrando fotos do resultado final.
B. Construa um mapa que represente o fluxo da utilização da solução proposta
pelo grupo, mostrando os pontos nos quais os componentes específicos da
solução são utilizados, dados são trocados e respostas são devolvidas
visualmente na forma de telas. Por exemplo: 1. o funcionário acessa uma
interface utilizando o seu notebook (o que aparece nesta interface?); 2. o
funcionário insere o comando na respectiva tela, pedindo para que o braço
robótico realize a separação de materiais (o mapa mostra que, da interface,
os comandos são enviados para um outro dispositivo: o braço mecânico); 3.
o braço realiza o processo de separação, depositando o conteúdo filtrado
numa bandeja; 4. o braço possui uma câmera embarcada e ele tira uma foto
que é enviada para a plataforma instalada no notebook (como esta imagem
aparece na interface?).
C. Além do mapeamento, como foi possível perceber pelos exemplos, o grupo
precisa apresentar as principais telas da sua proposta de solução, aqui
apresentadas no formato de um wireframe.

**Critérios de qualidade**
A entrega deverá ser realizada por meio da documentação na respectiva seção
apontada pelo template, contendo:

A. Contextualização da referida seção, mostrando entendimento da importância
deste processo de mapeamento (até 2,0 pontos);

B. Mapeamento completo, considerando ao menos uma User Story para cada
Persona. Ou seja: Caso o grupo tenha identificado duas Personas, serão
esperados dois mapas completos (até 2,0 pontos);
C. Representação de todos os dispositivos, componentes e conexões
relacionados ao fluxo mapeado (até 2,0 pontos);
D. Apresentação do wireframe das principais telas da solução, elaborados para
o(s) respectivo(s) dispositivo(s) que será(ão) acessado(s). Por exemplo:
desktop, notebook, celular, tablet, etc (até 2,0 pontos);
E. Textos e diagramas em conformidade e coerência com as etapas anteriores
do projeto, bem como descritos com corretude de regras gramaticais e
ortográficas (até 2,0 pontos).

https://drive.google.com/file/d/1kALlRapte63KtoKdta9Eu_0C8csGGKoc/view
