### ISSUE TITLE
Interface Navegável

### ISSUE THREAD

**Issue by rafaelarojas** [Inteli-College/2024-T0008-EC05-G03#55]
Para esta entrega é esperada a apresentação de um protótipo em alta fidelidade navegável ou da interface funcional já implementada à plataforma da solução proposta. Aqui, estamos considerando o conceito de "Responsive Design" como a adaptabilidade da solução nas diversas telas dos dispositivos nos quais a plataforma deverá ser acessada. 

Padrão de entrega:

Para informações detalhadas das requisições deste artefato, acesse: 
https://drive.google.com/file/d/10v1eyResfv_89G39XV8kjJA25ZtnLyW9/view?usp=sharing 

Padrão de qualidade:

Para informações detalhadas dos critérios de qualidade deste artefato, acesse: 
https://drive.google.com/file/d/10v1eyResfv_89G39XV8kjJA25ZtnLyW9/view?usp=sharing

**Comment by rafaelarojas** [comment]
Meio que já está pronto, mas acho válido perguntar pro Murilo se realmente é necessário a responsividade, visto que nossa solução só irá ser utilizada em um computador

**Comment by laurapbueno** [comment]
- [ ] design responsivo
- [ ] navegabilidade e usabilidade
- [ ] consistência com o wireframe
- [ ] identidade visual
